# Generated by Django 3.2.5 on 2021-10-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todov1', '0004_todos_addt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='todo',
            field=models.TextField(default='placeholder', verbose_name='Todos'),
            preserve_default=False,
        ),
    ]
