# Generated by Django 3.2.5 on 2021-10-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todov1', '0003_auto_20211013_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='addt',
            field=models.TextField(null=True, verbose_name='Additional data'),
        ),
    ]
